### ISSUE TITLE
Change tfstate resource location (Azure)

### ISSUE THREAD

**Issue by madakralc** [XenitAB/github-actions#31]
I do not know if this is needed in AWS envs, but would be good in an Azure implementation.

A solution might be to add a new variable for the prepare statement:
make prepare env=ENV dir=DIR state=swedencentral

**Comment by madakralc** [comment]
@simongottschlag Good idea?

**Comment by bittrance** [comment]
@madakralc I assume you want to control [`RG_LOCATION_{SHORT|LONG}`](https://github.com/XenitAB/github-actions/blob/48cf4d3bb4c76cc68498ce29f060edeb26445ba7/docker/terraform.sh#L10-L11). Can you describe the use case?

**Comment by madakralc** [comment]
@bittrance Correct. Without putting too much thought into it I can identify three quite obvious use cases.

1. A customer/implementation needs to put all data, information, and configuration in one region only - for example Sweden Central. As of today we would still have to put our remote state in West Europe as that is hard coded.
2. Quota limitation in hard coded Azure region for remote state
3. Legal and/or compliance requirements 

By the way, who are you Mr. Bittrance? Very mysterious!

**Comment by simongottschlag** [comment]
@madakralc released: https://github.com/XenitAB/github-actions/releases/tag/2021.10.1
